### PR TITLE
Demo updates for pyxem-0.9.0

### PR DESCRIPTION
**Pull request by dnjohnstone**

### CODE REVIEW

**Comment by dnjohnstone** [comment]
@pc494 - I couldn't work out quickly how to update the strain demo for your new changes. Please could you do that and make a PR to this branch?

Also it seems to me the update to the decomposition methods to try and get class assignment correct from @hwagit didn't work in the case used in the demo, which I don't quite understand....

**Comment by pc494** [comment]
Yep, will get a local copy of the branch, review & then add changes + make PR

**Comment by hwagit** [comment]
Which notebook, the Basic SED Analysis - GaAs Nanowire? I haven't run through the full notebook, but calling `s.change_dtype(float` changes data type to `Signal2D`. I use `s.data = s.data.astype(float)` myself. Might that be the cause? Using this instead and calling `decompositon()` on it now maintains the `ElectronDiffraction2D` class in my case.

**Comment by dnjohnstone** [comment]
> Which notebook, the Basic SED Analysis - GaAs Nanowire? I haven't run through the full notebook, but calling `s.change_dtype(float)` changes data type to `Signal2D`. I use `s.data = s.data.astype(float)` myself. Might that be the cause? Using this instead and calling `decompositon()` on it now maintains the `ElectronDiffraction2D` class in my case.

Ah - yes, that's almost certainly the cause. Thank you!

I guess that's a 'bug' with .change_dtype in pyxem then - which is probably to be resolved in a similar way to the previous decomposition bug?

**Pull request merged**
