### PR TITLE
V0.10.0

### PR DESCRIPTION
**Pull request by dnjohnstone**

### CODE REVIEW

**Comment by dnjohnstone** [comment]
demo 02 is currently not correct for pattern matching. I think that this is due to pyxem#492 changing how the library should be generated.

**Comment by dnjohnstone** [comment]
demo04 also has a pattern matching bug due to #492
demo05 may have a bug in vector based strain mapping, unsure where that's from though
demo06 also has some bugs linked to the final PR needed for 0.10.0

**Comment by dnjohnstone** [comment]
@pc494 please could you have a look at demo 2 and 4 on this branch and update them for the new template library generation behaviour.

Please could you also look at 5 and see if you agree there is an issue in the vector based strain mapping?

If those are tied up then I think we just have the nanocrystal segmentation to finish for 0.10.0

**Comment by pc494** [comment]
Changing the `center_of_mass_method()` argument to `20` (ie - larger square investigated) seems to fix the problem in Book 5.

**Pull request merged**
